version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "80:80" # testing port TODO: remove
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - wordpress_network

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    depends_on:
      - mariadb
      - redis
    expose:
      - '9000'
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mariadb_network
      - wordpress_network
      - redis_network
      - vsftp_network
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_ADDRESS: ${WP_ADDRESS}
      WP_TITLE: ${WP_TITLE}
      REDIS_PASS: ${REDIS_PASS}

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - mariadb_network

  redis:
    image: redis
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    restart: always
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - wordpress_db:/var/lib/html
      - redis_output:/etc
    environment:
      REDIS_PASS: ${REDIS_PASS}
    networks:
      - redis_network

  # vsftp:
  #   image: vsftp
  #   container_name: vsftp
  #   build:
  #     context: ./requirements/bonus/ftp
  #   restart: always
  #   networks:
  #     - vsftp_network
  #   volumes:
  #     - wordpress_files:/var/www/html
  #   environment:
  #     FTP_USER: ${FTP_USER}
  #     FTP_PASS: ${FTP_PASS}

  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   build:
  #     context: ./requirements/bonus/adminer
  #   volumes:
  #     - wordpress_files:/var/www/html


volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind
  redis_output:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/redis
      o: bind

networks:
  wordpress_network:
  mariadb_network:
  redis_network:
  vsftp_network:
