version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - wordpress_network

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    depends_on:
      - mairadb
      # - redis
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - mariadb_network
      - wordpress_network
    ports:
      - "9000:9000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
      WP_ADDRESS: ${WP_ADDRESS}
      WP_TITLE: ${WP_TITLE}
      REDIS_PASS: ${REDIS_PASS}

  mairadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      DB_NAME: ${DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOTPASSWORD: ${MYSQL_ROOTPASSWORD}
    networks:
      - mariadb_network

  # redis:
  #   image: redis
  #   container_name: redis
  #   build:
  #     context: ./requirements/bonus/redis
  #   restart: always
  #   volumes:
  #     - wordpress_db:/var/lib/html
  #   environment:
  #     REDIS_PASS: ${REDIS_PASS}
  #   networks:
  #     - wordpress_network

  # vsftp:
  #   image: vsftp
  #   container_name: vsftp
  #   build:
  #     context: ./requirements/bonus/ftp
  #   restart: always
  #   networks:
  #     - wordpress_network
  #   volumes:
  #     - wordpress_files:/var/www/html
  #   env_file:
  #     - .env

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mysql
      o: bind
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  wordpress_network:
  mariadb_network:
