version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - wordpress_network

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    restart: always
    depends_on:
      - mairadb
      - redis
    volumes:
      - wordpress_files:/var/www/html
      - wordpress_db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wordpress_network
      - mariadb_network

  mairadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - mariadb_network

  redis:
    image: redis
    container_name: redis
    build:
      context: ./requirements/bonus/redis
    restart: always
    env_file:
      - .env
    networks:
      - wordpress_network

  vsftp:
    image: vsftp
    container_name: vsftp
    build:
      context: ./requirements/bonus/ftp
    restart: always
    volumes:
      - wordpress_files:/var/www/inception
    env_file:
      - .env

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mysql
      o: bind
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  wordpress_network:
  mariadb_network:
